name: musical
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^1.2.2
  flutter_dotenv: ^5.2.1

  webview_flutter_android: ^4.0.2
  webview_flutter_wkwebview: ^3.16.2
  webview_flutter: ^4.2.1

  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_database: ^11.1.6
  flutter_calendar_carousel: ^2.4.4
  spotify_sdk: ^3.0.2
  url_launcher: ^6.3.1

  loading_animation_widget: ^1.3.0

  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0
  shared_preferences: ^2.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.1"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/musiCAL icon.jpeg"
